<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "access_token".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $consumer
 * @property string $token
 * @property string $access_given
 * @property integer $used_at
 * @property integer $expire_at
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class AccessToken extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'access_token';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'used_at', 'expire_at', 'created_at', 'updated_at'], 'integer'],
            [['token', 'created_at', 'updated_at'], 'required'],
            [['access_given'], 'string'],
            [['consumer'], 'string', 'max' => 255],
            [['token'], 'string', 'max' => 32],
            [['token'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'consumer' => 'Consumer',
            'token' => 'Token',
            'access_given' => 'Access Given',
            'used_at' => 'Used At',
            'expire_at' => 'Expire At',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\AccessTokenQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\AccessTokenQuery(get_called_class());
    }


}
