<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "post".
 *
 * @property integer $id
 * @property string $title
 * @property string $body
 * @property string $aliasModel
 */
abstract class Post extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'post';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['body'], 'string'],
            [['title'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'body' => 'Body',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\PostQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\PostQuery(get_called_class());
    }


}
