<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "rooms".
 *
 * @property integer $id
 * @property string $name
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\StudentRoom[] $studentRooms
 * @property string $aliasModel
 */
abstract class Room extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'rooms';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required', "message" => "{attribute} không được bỏ trống"],
            [['name', 'created_at', 'updated_at'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Tên Phòng',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudentRooms()
    {
        return $this->hasMany(\app\models\StudentRoom::className(), ['room_id' => 'id']);
    }



    /**
     * @inheritdoc
     * @return \app\models\RoomQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\RoomQuery(get_called_class());
    }
}
