<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "student_rooms".
 *
 * @property integer $id
 * @property integer $student_id
 * @property integer $room_id
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\Room $room
 * @property \app\models\Student $student
 * @property string $aliasModel
 */
abstract class StudentRoom extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'student_rooms';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['student_id', 'room_id'], 'required'],
            [['student_id', 'room_id'], 'integer'],
            [['created_at', 'updated_at'], 'string', 'max' => 200],
            [['student_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Student::className(), 'targetAttribute' => ['student_id' => 'id']],
            [['room_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Room::className(), 'targetAttribute' => ['room_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'student_id' => 'Student ID',
            'room_id' => 'Room ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRoom()
    {
        return $this->hasOne(\app\models\Room::className(), ['id' => 'room_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudent()
    {
        return $this->hasOne(\app\models\Student::className(), ['id' => 'student_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\StudentRoomQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\StudentRoomQuery(get_called_class());
    }


}
