<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "subjects".
 *
 * @property integer $id
 * @property string $name
 * @property string $created_at
 * @property string $updated_att
 *
 * @property \app\models\StudentSubject[] $studentSubjects
 * @property string $aliasModel
 */
abstract class Subject extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'subjects';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name', 'created_at', 'updated_att'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'created_at' => 'Created At',
            'updated_att' => 'Updated Att',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudentSubjects()
    {
        return $this->hasMany(\app\models\StudentSubject::className(), ['subject_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\SubjectQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\SubjectQuery(get_called_class());
    }


}
